SPECIES_SEED_DATA = [
    {
        "common_name": "Bengal Tiger",
        "scientific_name": "Panthera tigris tigris",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "P. tigris tigris",
        "iucn_status": "Endangered",
        "habitat": "Forests, Mangroves, Grasslands",
        "diet": "Carnivore",
        "distribution": "India, Nepal, Bhutan, Bangladesh",
        "description": "The Bengal tiger is a tiger population native to the Indian subcontinent. It is the national animal of India and plays a key role as an apex predator in dry/moist deciduous and mangrove ecosystems."
    },
    {
        "common_name": "Indian Leopard",
        "scientific_name": "Panthera pardus fusca",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "P. pardus",
        "iucn_status": "Vulnerable",
        "habitat": "Forests, Grasslands, Rocky terrains, Scrublands",
        "diet": "Carnivore",
        "distribution": "Indian subcontinent",
        "description": "The Indian leopard is a leopard subspecies widely distributed on the Indian subcontinent. It is a highly adaptable predator, coexisting with other large carnivores like tigers."
    },
    {
        "common_name": "Asian Elephant",
        "scientific_name": "Elephas maximus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Proboscidea",
        "family": "Elephantidae",
        "genus": "Elephas",
        "species": "E. maximus",
        "iucn_status": "Endangered",
        "habitat": "Forests, Grasslands, Scrublands",
        "diet": "Herbivore",
        "distribution": "Southeast and South Asia",
        "description": "The Asian elephant is the largest living land animal in Asia. It is considered an ecosystem engineer, modifying habitats and dispersing seeds across forests and grasslands."
    },
    {
        "common_name": "Asiatic Lion",
        "scientific_name": "Panthera leo persica",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "P. leo",
        "iucn_status": "Endangered",
        "habitat": "Dry Deciduous Forest, Scrubland",
        "diet": "Carnivore",
        "distribution": "Gir National Park, Gujarat, India",
        "description": "The Asiatic lion is a Panthera leo leo population surviving today only in Gir Forest and its surrounding areas in Gujarat, India."
    },
    {
        "common_name": "One-horned Rhinoceros",
        "scientific_name": "Rhinoceros unicornis",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Perissodactyla",
        "family": "Rhinocerotidae",
        "genus": "Rhinoceros",
        "species": "R. unicornis",
        "iucn_status": "Vulnerable",
        "habitat": "Alluvial Grasslands, Riverine Forests",
        "diet": "Herbivore",
        "distribution": "Assam, India and Nepal",
        "description": "The Indian rhinoceros, also called the greater one-horned rhinoceros, is native to the Indian subcontinent. It is primarily found in Kaziranga National Park."
    },
    {
        "common_name": "Indian Peafowl",
        "scientific_name": "Pavo cristatus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Galliformes",
        "family": "Phasianidae",
        "genus": "Pavo",
        "species": "P. cristatus",
        "iucn_status": "Least Concern",
        "habitat": "Forests, Woodlands, Cultivated Areas",
        "diet": "Omnivore",
        "distribution": "South Asia",
        "description": "The Indian peafowl (peacock) is the national bird of India, celebrated for its colorful fan of train feathers."
    },
    {
        "common_name": "Wild Boar",
        "scientific_name": "Sus scrofa",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Suidae",
        "genus": "Sus",
        "species": "S. scrofa",
        "iucn_status": "Least Concern",
        "habitat": "Forests, Grasslands, Agricultural Areas",
        "diet": "Omnivore",
        "distribution": "Widespread across India and Eurasia",
        "description": "The wild boar is a highly adaptable omnivorous mammal native to much of Eurasia, North Africa, and the Greater Sunda Islands."
    },
    {
        "common_name": "Sloth Bear",
        "scientific_name": "Melursus ursinus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ursidae",
        "genus": "Melursus",
        "species": "M. ursinus",
        "iucn_status": "Vulnerable",
        "habitat": "Forests, Scrublands, Grasslands",
        "diet": "Omnivore",
        "distribution": "Indian subcontinent",
        "description": "The sloth bear is a myrmecophagous bear species native to the Indian subcontinent. It feeds mainly on termites and ants."
    },
    {
        "common_name": "Indian Gaur",
        "scientific_name": "Bos gaurus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Bos",
        "species": "B. gaurus",
        "iucn_status": "Vulnerable",
        "habitat": "Forests, Bamboo Thickets, Grasslands",
        "diet": "Herbivore",
        "distribution": "South and Southeast Asia",
        "description": "The gaur, also called the Indian bison, is the largest species of wild cattle in the world. It is native to South and Southeast Asia."
    },
    {
        "common_name": "Chital",
        "scientific_name": "Axis axis",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Cervidae",
        "genus": "Axis",
        "species": "A. axis",
        "iucn_status": "Least Concern",
        "habitat": "Deciduous Forests, Meadows, Scrublands",
        "diet": "Herbivore",
        "distribution": "Indian subcontinent",
        "description": "The chital, also known as the spotted deer, is a deer species native to the Indian subcontinent. It is a highly social ungulate."
    },
    {
        "common_name": "Sambar Deer",
        "scientific_name": "Rusa unicolor",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Cervidae",
        "genus": "Rusa",
        "species": "R. unicolor",
        "iucn_status": "Vulnerable",
        "habitat": "Forests, Mountains, Woodlands",
        "diet": "Herbivore",
        "distribution": "Indian subcontinent and Southeast Asia",
        "description": "The sambar is a large deer native to the Indian subcontinent, southern China, and Southeast Asia. It is a key prey species for tigers."
    },
    {
        "common_name": "Nilgai",
        "scientific_name": "Boselaphus tragocamelus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Boselaphus",
        "species": "B. tragocamelus",
        "iucn_status": "Least Concern",
        "habitat": "Dry scrub, semi-deserts, open agricultural lands",
        "diet": "Herbivore",
        "distribution": "Indian subcontinent",
        "description": "The nilgai or blue bull is the largest Asian antelope and is endemic to the Indian subcontinent."
    },
    {
        "common_name": "Dhole",
        "scientific_name": "Cuon alpinus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Canidae",
        "genus": "Cuon",
        "species": "C. alpinus",
        "iucn_status": "Endangered",
        "habitat": "Forests, Alpine Zones, Grasslands",
        "diet": "Carnivore",
        "distribution": "South, East, and Southeast Asia",
        "description": "The dhole is a canid native to Central, South, East, and Southeast Asia. It is a highly social pack hunter."
    }
]
