import json
import os

catalog_path = "backend/data/species_catalog.json"

# Complete biological info for all 64 classes
class_data = {
    "Bear": {
        "common_name": "Bear",
        "scientific_name": "Ursidae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ursidae",
        "genus": "Ursus",
        "species": "Ursus americanus",
        "habitat": "Forests, mountains, and swamps",
        "distribution": "North America, Europe, Asia, and South America",
        "diet": "Omnivorous, feeding on berries, roots, insects, fish, and mammals",
        "description": "Large, powerful mammals with shaggy fur, short tails, and excellent sense of smell.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect large contiguous forest tracts and promote bear-proof waste management.",
        "human_wildlife_conflict_risk": "Medium risk of property damage and crop raiding.",
        "anti_poaching_recommendation": "Monitor forest boundaries and penalize illegal baiting.",
        "behaviour_hints": "Solitary, excellent climbers and swimmers, active during day and night."
    },
    "Brown-bear": {
        "common_name": "Brown Bear",
        "scientific_name": "Ursus arctos",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ursidae",
        "genus": "Ursus",
        "species": "Ursus arctos",
        "habitat": "Tundra, alpine meadows, and dense temperate forests",
        "distribution": "Northern North America, Europe, and northern Asia",
        "diet": "Omnivorous, consuming vegetation, fish (salmon), small mammals, and carrion",
        "description": "A very large bear species distinguished by a muscular shoulder hump and long claws.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Reduce human encroachment in alpine zones and enforce fish harvesting limits.",
        "human_wildlife_conflict_risk": "High risk of confrontation during salmon runs or near campgrounds.",
        "anti_poaching_recommendation": "Conduct regular patrols along salmon rivers and mountain passes.",
        "behaviour_hints": "Crepuscular or nocturnal, digs dens for winter hibernation."
    },
    "Bull": {
        "common_name": "Gaur",
        "scientific_name": "Bos gaurus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Bos",
        "species": "Bos gaurus",
        "habitat": "Deciduous forests, evergreen forests, and grassy clearings",
        "distribution": "South and Southeast Asia, primarily India",
        "diet": "Herbivorous, grazing on grasses, bamboo shoots, and shrubs",
        "description": "Also known as the Indian Bison, the Gaur is the largest species of wild cattle in the world.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Restore grassland habitats and vaccinate domestic livestock to prevent disease transmission.",
        "human_wildlife_conflict_risk": "Low to medium risk, occasionally damages crops near forest borders.",
        "anti_poaching_recommendation": "Enforce strict protection laws in national parks and check meat markets.",
        "behaviour_hints": "Diurnal in undisturbed areas, forms herds led by an old matriarch."
    },
    "Butterfly": {
        "common_name": "Butterfly",
        "scientific_name": "Lepidoptera",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Insecta",
        "order": "Lepidoptera",
        "family": "Nymphalidae",
        "genus": "Vanessa",
        "species": "Vanessa cardui",
        "habitat": "Meadows, gardens, forests, and agricultural fields",
        "distribution": "Worldwide, except Antarctica",
        "diet": "Nectarivorous, feeding on flower nectar and rotting fruit juices",
        "description": "Day-active insects characterized by large, often brightly colored wings and a coiled proboscis.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Avoid pesticide use and plant native flowering vegetation.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Prevent illegal specimen collection in protected reserves.",
        "behaviour_hints": "Fluttering flight, mud-puddling on damp soil for minerals."
    },
    "Camel": {
        "common_name": "Camel",
        "scientific_name": "Camelus dromedarius",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Camelidae",
        "genus": "Camelus",
        "species": "Camelus dromedarius",
        "habitat": "Arid deserts, grasslands, and scrublands",
        "distribution": "Northern Africa, Middle East, Central Asia, and introduced to Australia",
        "diet": "Herbivorous, browsing on thorny desert vegetation, dry grasses, and saltbushes",
        "description": "Large even-toed ungulates with distinctive humps containing fat reserves for desert survival.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Manage grazing lands and maintain traditional migration corridors.",
        "human_wildlife_conflict_risk": "Low risk, occasional grazing competition with local livestock.",
        "anti_poaching_recommendation": "Prevent desert vehicle tracks in fragile desert ecosystems.",
        "behaviour_hints": "Form herds led by a dominant male, store water efficiently."
    },
    "Canary": {
        "common_name": "Canary",
        "scientific_name": "Serinus canaria",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Passeriformes",
        "family": "Fringillidae",
        "genus": "Serinus",
        "species": "Serinus canaria",
        "habitat": "Open woodlands, scrublands, orchards, and gardens",
        "distribution": "Canary Islands, Azores, and Madeira; domesticated worldwide",
        "diet": "Granivorous, feeding primarily on seeds, weed seeds, and small insects",
        "description": "A small passerine bird in the finch family, famous for its melodious singing voice.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain shrublands and regulate songbird capture for pet trade.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Patrol nesting locations to prevent illegal cage collection.",
        "behaviour_hints": "Very active, gregarious, sings from high perches to defend territory."
    },
    "Cat": {
        "common_name": "Cat",
        "scientific_name": "Felis catus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Felis",
        "species": "Felis catus",
        "habitat": "Urban areas, suburban gardens, forests, and grasslands",
        "distribution": "Worldwide, domesticated and feral populations",
        "diet": "Carnivorous, preying on small rodents, birds, reptiles, and insects",
        "description": "A small carnivorous mammal domestic animal kept as a pet or working predator.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Implement trap-neuter-return programs to protect local wild birds.",
        "human_wildlife_conflict_risk": "Feral cats represent a major threat to native birds and small mammals.",
        "anti_poaching_recommendation": "No anti-poaching measures required; protect wild cats from domestic hybridization.",
        "behaviour_hints": "Agile, nocturnal, uses scratching posts for territory marking."
    },
    "Caterpillar": {
        "common_name": "Caterpillar",
        "scientific_name": "Lepidoptera Larva",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Insecta",
        "order": "Lepidoptera",
        "family": "Noctuidae",
        "genus": "Spodoptera",
        "species": "Spodoptera frugiperda",
        "habitat": "Forests, meadows, crops, and home gardens",
        "distribution": "Global distribution",
        "diet": "Herbivorous, chewing leaves, stems, flowers, and fruits of host plants",
        "description": "The larval stage of a member of the insect order Lepidoptera (butterflies and moths).",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain vegetation diversity to avoid pest outbreaks.",
        "human_wildlife_conflict_risk": "Can cause high agricultural damage to crop foliage.",
        "anti_poaching_recommendation": "Monitor forest understory conditions.",
        "behaviour_hints": "Slow crawling, uses camouflage, mimicry, or toxicity to repel predators."
    },
    "Cattle": {
        "common_name": "Cattle",
        "scientific_name": "Bos taurus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Bos",
        "species": "Bos taurus",
        "habitat": "Pastures, grasslands, and agricultural fields",
        "distribution": "Worldwide, domestic livestock",
        "diet": "Herbivorous, grazing on grasses, clover, and herbaceous plants",
        "description": "Domesticated bovine mammals reared for dairy, meat, leather, and draught power.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Manage grazing density to prevent soil erosion and degradation of wild habitats.",
        "human_wildlife_conflict_risk": "Attracts large wild predators (lions, tigers), leading to retaliatory killing.",
        "anti_poaching_recommendation": "Check border fences around protected tiger reserves.",
        "behaviour_hints": "Forms cohesive herds with a clear social structure, spends hours ruminating."
    },
    "Centipede": {
        "common_name": "Centipede",
        "scientific_name": "Chilopoda",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Chilopoda",
        "order": "Scolopendromorpha",
        "family": "Scolopendridae",
        "genus": "Scolopendra",
        "species": "Scolopendra gigantea",
        "habitat": "Leaf litter, under stones, decaying wood, and caves",
        "distribution": "Worldwide, primarily in tropical and temperate climates",
        "diet": "Carnivorous, preying on insects, spiders, worms, and small vertebrates",
        "description": "Elongated metameric arthropods with one pair of legs per body segment, equipped with venom claws.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Preserve forest ground leaf litter and decaying log piles.",
        "human_wildlife_conflict_risk": "Low risk; possess venomous bites that cause pain and swelling.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, extremely fast runner, seeks damp dark shelters."
    },
    "Cheetah": {
        "common_name": "Cheetah",
        "scientific_name": "Acinonyx jubatus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Acinonyx",
        "species": "Acinonyx jubatus",
        "habitat": "Savannas, semi-deserts, and open grassy plains",
        "distribution": "Sub-Saharan Africa and reintroduced to parts of India",
        "diet": "Carnivorous, preying on small to medium ungulates like gazelles and impalas",
        "description": "The fastest land mammal, characterized by a slender body, spotted coat, and tear-like facial streaks.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Prevent land fragmentation, reduce poaching of prey, and resolve livestock conflicts.",
        "human_wildlife_conflict_risk": "Low risk; rarely attacks humans but conflicts occur over domestic livestock.",
        "anti_poaching_recommendation": "Use GPS tracking collars, check snare traps, and expand wildlife reserves.",
        "behaviour_hints": "Diurnal hunter, relies on high-speed chases, climbs low branches to spot prey."
    },
    "Chicken": {
        "common_name": "Chicken",
        "scientific_name": "Gallus gallus domesticus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Galliformes",
        "family": "Phasianidae",
        "genus": "Gallus",
        "species": "Gallus gallus",
        "habitat": "Farms, gardens, agricultural fields, and backyards",
        "distribution": "Worldwide, domestic species",
        "diet": "Omnivorous, feeding on seeds, grains, leaves, worms, and insects",
        "description": "A type of domesticated fowl, widely kept for its meat and eggs.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Implement bio-security measures to prevent transmission of avian flu to wild bird populations.",
        "human_wildlife_conflict_risk": "Attracts wild birds of prey, foxes, and wild cats.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Scratches ground with feet, roosts on elevated branches at night."
    },
    "Deer": {
        "common_name": "Deer",
        "scientific_name": "Cervidae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Cervidae",
        "genus": "Cervus",
        "species": "Cervus elaphus",
        "habitat": "Forests, grasslands, and wetlands",
        "distribution": "Global distribution",
        "diet": "Herbivorous, consuming grasses, leaves, bark, and twigs",
        "description": "Hoofed ruminants characterized by antlers in males, which are shed and regrown annually.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Control deer densities through managed hunting or natural predators to preserve vegetation.",
        "human_wildlife_conflict_risk": "Medium risk of vehicle collisions and agricultural crop raiding.",
        "anti_poaching_recommendation": "Monitor forest fringes and penalize illegal night hunting.",
        "behaviour_hints": "Forms herds, crepuscular, highly alert with excellent hearing."
    },
    "Dog": {
        "common_name": "Dog",
        "scientific_name": "Canis lupus familiaris",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Canidae",
        "genus": "Canis",
        "species": "Canis lupus",
        "habitat": "Human settlements, farms, grasslands, and woodlands",
        "distribution": "Worldwide, domestic and feral populations",
        "diet": "Omnivorous, eating meat, grains, vegetables, and prepared commercial feed",
        "description": "Domesticated carnivore of the family Canidae, closely related to the gray wolf.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Enforce vaccination against rabies and limit feral dog entry into wildlife sanctuaries.",
        "human_wildlife_conflict_risk": "Feral dogs compete with wild predators and pack-hunt wildlife species.",
        "anti_poaching_recommendation": "Prevent domestic dog packs from roaming deep into tiger reserves.",
        "behaviour_hints": "Highly social, pack behavior, uses scent marking and vocalizations."
    },
    "Duck": {
        "common_name": "Duck",
        "scientific_name": "Anatidae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Anseriformes",
        "family": "Anatidae",
        "genus": "Anas",
        "species": "Anas platyrhynchos",
        "habitat": "Ponds, lakes, rivers, marshes, and coastal waters",
        "distribution": "Worldwide, except Antarctica",
        "diet": "Omnivorous, consuming aquatic plants, small fish, insects, and seeds",
        "description": "Waterfowl characterized by webbed feet, broad bills, and waterproof feathers.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Restore wetlands, prevent chemical runoffs, and ban lead shot hunting.",
        "human_wildlife_conflict_risk": "Low risk, occasional crop damage in flooded rice fields.",
        "anti_poaching_recommendation": "Enforce hunting seasons and inspect wetland reserves.",
        "behaviour_hints": "Dabbles or dives for food, migrates in V-formations, preens feathers constantly."
    },
    "Eagle": {
        "common_name": "Eagle",
        "scientific_name": "Accipitridae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Accipitriformes",
        "family": "Accipitridae",
        "genus": "Aquila",
        "species": "Aquila chrysaetos",
        "habitat": "Mountains, crags, forests, and coastal cliffs",
        "distribution": "Global distribution",
        "diet": "Carnivorous, preying on small mammals, fish, birds, and carrion",
        "description": "Large, powerfully built birds of prey with heavy hooked beaks and keen eyesight.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect old-growth nesting trees and reduce use of toxic pesticides like DDT.",
        "human_wildlife_conflict_risk": "Low risk; occasionally preys on poultry or domestic lambs.",
        "anti_poaching_recommendation": "Establish strict penalties for shooting birds of prey and protect nesting sites.",
        "behaviour_hints": "Soars on thermal wind currents, constructs huge stick nests called eyries."
    },
    "Elephant": {
        "common_name": "Asian Elephant",
        "scientific_name": "Elephas maximus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Proboscidea",
        "family": "Elephantidae",
        "genus": "Elephas",
        "species": "Elephas maximus",
        "habitat": "Tropical forests, woodlands, and grasslands",
        "distribution": "South and Southeast Asia, including India",
        "diet": "Herbivorous, consuming grass, tree bark, roots, leaves, and agricultural crops",
        "description": "The largest land animal in Asia, recognizable by its long trunk, tusks, and large ears.",
        "iucn_status": "Endangered",
        "threat_level": "High",
        "conservation_priority": "Critical",
        "protection_recommendation": "Establish dedicated wildlife corridors, mitigate train collisions, and create buffer zones.",
        "human_wildlife_conflict_risk": "High risk due to crop raiding and trampling of houses near forest borders.",
        "anti_poaching_recommendation": "Patrol borders, use drone surveillance, and track ivory trading networks.",
        "behaviour_hints": "Highly social, matriarchal family groups, communicates through infrasound."
    },
    "Fox": {
        "common_name": "Fox",
        "scientific_name": "Vulpes vulpes",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Canidae",
        "genus": "Vulpes",
        "species": "Vulpes vulpes",
        "habitat": "Forests, scrublands, deserts, and urban parks",
        "distribution": "Northern Hemisphere and introduced to Australia",
        "diet": "Omnivorous, feeding on rodents, rabbits, insects, fruits, and garbage",
        "description": "Small-to-medium omnivorous mammals characterized by a bushy tail, pointed snout, and erect ears.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Promote rabbit control in areas where foxes compete with native carnivores.",
        "human_wildlife_conflict_risk": "Low-medium risk, commonly raids chicken coops and digs in trash bins.",
        "anti_poaching_recommendation": "Monitor border traps and restrict night spotlighting.",
        "behaviour_hints": "Nocturnal or crepuscular, solitary hunter, uses pouncing jumps to catch prey."
    },
    "Frog": {
        "common_name": "Frog",
        "scientific_name": "Anura",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Amphibia",
        "order": "Anura",
        "family": "Ranidae",
        "genus": "Rana",
        "species": "Rana temporaria",
        "habitat": "Wetlands, ponds, rainforests, and damp woodlands",
        "distribution": "Worldwide, except polar regions",
        "diet": "Insectivorous, catching flies, moths, beetles, and worms with sticky tongue",
        "description": "Tailless amphibians with protruding eyes and long hind legs adapted for jumping.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect freshwater vernal pools and minimize agricultural pesticide runoff.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Ensure protection against commercial harvesting for food or pet trade.",
        "behaviour_hints": "Nocturnal calling to attract mates, undergoes metamorphosis from tadpole."
    },
    "Giraffe": {
        "common_name": "Giraffe",
        "scientific_name": "Giraffa camelopardalis",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Giraffidae",
        "genus": "Giraffa",
        "species": "Giraffa camelopardalis",
        "habitat": "Dry savannas and open acacia woodlands",
        "distribution": "Sub-Saharan Africa",
        "diet": "Herbivorous, browsing on leaves (particularly acacia), twigs, and fruits",
        "description": "The tallest living terrestrial animal, known for its extremely long neck and spotted skin pattern.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Secure acacia woodlands and prevent illegal firewood extraction.",
        "human_wildlife_conflict_risk": "Low risk; occasionally damages tall crops or power lines.",
        "anti_poaching_recommendation": "Perform regular patrols and dismantle wire snares.",
        "behaviour_hints": "Social, forms loose herds, sleeps standing up, uses prehensile tongue to pick leaves."
    },
    "Goat": {
        "common_name": "Goat",
        "scientific_name": "Capra hircus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Capra",
        "species": "Capra hircus",
        "habitat": "Mountainous regions, grasslands, scrublands, and farms",
        "distribution": "Worldwide, domestic species",
        "diet": "Herbivorous, browsing on shrubs, weeds, leaves, and woody plants",
        "description": "Hardy domesticated bovines, primarily kept for their milk, meat, and fiber.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Control grazing in sensitive mountain habitats to prevent desertification.",
        "human_wildlife_conflict_risk": "Competes with wild mountain ungulates for scarce food.",
        "anti_poaching_recommendation": "Coordinate pasture boundaries near high-altitude wild goat reserves.",
        "behaviour_hints": "Excellent climber, curious and agile, investigates surroundings constantly."
    },
    "Goose": {
        "common_name": "Goose",
        "scientific_name": "Anserinae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Anseriformes",
        "family": "Anatidae",
        "genus": "Anser",
        "species": "Anser anser",
        "habitat": "Lakes, rivers, marshes, estuaries, and agricultural fields",
        "distribution": "Northern Hemisphere, migrating globally",
        "diet": "Herbivorous, grazing on grasses, grains, roots, and aquatic plants",
        "description": "Medium-to-large waterfowl in the family Anatidae, larger than ducks but smaller than swans.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect nesting wetlands and regulate public feeding spots to prevent disease.",
        "human_wildlife_conflict_risk": "Low risk, can be aggressive in parks during nesting season.",
        "anti_poaching_recommendation": "Verify waterbird hunting quotas during open seasons.",
        "behaviour_hints": "Very protective of nests, loud honking alarm calls, migrates in large flocks."
    },
    "Hamster": {
        "common_name": "Hamster",
        "scientific_name": "Cricetinae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Rodentia",
        "family": "Cricetidae",
        "genus": "Mesocricetus",
        "species": "Mesocricetus auratus",
        "habitat": "Grasslands, semi-deserts, agricultural borders, and homes",
        "distribution": "Europe and Asia; domesticated worldwide as pets",
        "diet": "Omnivorous, feeding on seeds, grains, grass, vegetation, and small insects",
        "description": "Small rodents characterized by large cheek pouches used to carry food and short tails.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain native grasslands and restrict commercial collection of wild species.",
        "human_wildlife_conflict_risk": "No conflict risk, occasionally digs tunnels in agricultural fields.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, solitary, hoards food in underground burrows."
    },
    "Hedgehog": {
        "common_name": "Hedgehog",
        "scientific_name": "Erinaceinae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Eulipotyphla",
        "family": "Erinaceidae",
        "genus": "Erinaceus",
        "species": "Erinaceus europaeus",
        "habitat": "Woodlands, scrublands, hedgerows, and suburban gardens",
        "distribution": "Europe, Asia, Africa, and introduced to New Zealand",
        "diet": "Insectivorous, feeding on beetles, caterpillars, slugs, snails, and worms",
        "description": "Small spiny mammals easily recognized by their protective coat of stiff spines.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Build wildlife tunnels under major roads and preserve backyard hedges.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, rolls into a tight ball when threatened, hibernates in winter."
    },
    "Hippopotamus": {
        "common_name": "Hippopotamus",
        "scientific_name": "Hippopotamus amphibius",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Hippopotamidae",
        "genus": "Hippopotamus",
        "species": "Hippopotamus amphibius",
        "habitat": "Rivers, lakes, and muddy wallows in woodland savannas",
        "distribution": "Sub-Saharan Africa",
        "diet": "Herbivorous, grazing on short grasses on riverbanks at night",
        "description": "A very large, semi-aquatic mammal known for its barrel-shaped torso and massive jaw.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Protect freshwater rivers, regulate water diversions, and ban ivory tooth trade.",
        "human_wildlife_conflict_risk": "High risk; highly aggressive and will attack boats or crops.",
        "anti_poaching_recommendation": "Establish boat patrols on lakes and check for illegal snare lines.",
        "behaviour_hints": "Submerges for up to 5 minutes, highly territorial in water but solitary on land."
    },
    "Horse": {
        "common_name": "Horse",
        "scientific_name": "Equus caballus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Perissodactyla",
        "family": "Equidae",
        "genus": "Equus",
        "species": "Equus caballus",
        "habitat": "Grasslands, pastures, and steppes",
        "distribution": "Worldwide, domestic and feral populations",
        "diet": "Herbivorous, grazing on grasses, weeds, and hay",
        "description": "Odd-toed ungulate mammal with a long mane and tail, domesticated for riding and draft work.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Ensure range management and protect natural grasslands from overgrazing.",
        "human_wildlife_conflict_risk": "Low risk, occasional crop damage if animals escape enclosures.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Forms bands (harems) led by a stallion, communicates via neighs and body language."
    },
    "Jellyfish": {
        "common_name": "Jellyfish",
        "scientific_name": "Medusozoa",
        "kingdom": "Animalia",
        "phylum": "Cnidaria",
        "class_name": "Scyphozoa",
        "order": "Semaeostomeae",
        "family": "Ulmaridae",
        "genus": "Aurelia",
        "species": "Aurelia aurita",
        "habitat": "Ocean surface, deep sea, and coastal waters",
        "distribution": "All oceans worldwide",
        "diet": "Carnivorous, preying on small fish, zooplankton, and other jellyfish",
        "description": "Gelatinous marine animals with bell-shaped bodies and trailing stinging tentacles.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Prevent marine plastic pollution and combat ocean acidification.",
        "human_wildlife_conflict_risk": "Sting swimmers and can clog power plant cooling water pipes.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Pulsates bell for vertical propulsion, drifts passive with ocean currents."
    },
    "Kangaroo": {
        "common_name": "Kangaroo",
        "scientific_name": "Macropus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Diprotodontia",
        "family": "Macropodidae",
        "genus": "Macropus",
        "species": "Macropus giganteus",
        "habitat": "Eucalyptus forests, grassy plains, and savannas",
        "distribution": "Australia",
        "diet": "Herbivorous, grazing on grasses, shrubs, and leaves",
        "description": "Large marsupials characterized by powerful hind legs, large feet, and a long muscular tail.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain native grasslands and establish wildlife-friendly fencing.",
        "human_wildlife_conflict_risk": "Low-medium risk, can collide with vehicles on rural highways.",
        "anti_poaching_recommendation": "Monitor commercial harvesting and check boundary fences.",
        "behaviour_hints": "Hops at high speeds, forms social groups called mobs, active at night and dusk."
    },
    "Koala": {
        "common_name": "Koala",
        "scientific_name": "Phascolarctos cinereus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Diprotodontia",
        "family": "Phascolarctidae",
        "genus": "Phascolarctos",
        "species": "Phascolarctos cinereus",
        "habitat": "Eucalyptus woodlands and forests",
        "distribution": "Eastern and southeastern Australia",
        "diet": "Herbivorous, feeding almost exclusively on eucalyptus leaves",
        "description": "Arboreal herbivorous marsupial native to Australia, known for its round ears and lack of a tail.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Protect eucalyptus forest habitat and build wildlife crossings over highways.",
        "human_wildlife_conflict_risk": "Low risk; dogs or vehicle strikes in peri-urban areas pose danger to koalas.",
        "anti_poaching_recommendation": "Set strict penalties for illegal land clearing and monitor fire spots.",
        "behaviour_hints": "Very inactive, sleeps up to 20 hours a day, excellent climber."
    },
    "Ladybug": {
        "common_name": "Ladybug",
        "scientific_name": "Coccinellidae",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Insecta",
        "order": "Coleoptera",
        "family": "Coccinellidae",
        "genus": "Coccinella",
        "species": "Coccinella septempunctata",
        "habitat": "Gardens, agricultural crops, grasslands, and deciduous forests",
        "distribution": "Global distribution",
        "diet": "Carnivorous, preying on aphids, scale insects, and mites",
        "description": "Small dome-shaped beetles with red or yellow wing covers marked with black spots.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Avoid broad-spectrum chemical insecticides to preserve beneficial ladybugs.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Emits yellow fluid when handled, hibernates in large clusters under bark."
    },
    "Leopard": {
        "common_name": "Indian Leopard",
        "scientific_name": "Panthera pardus fusca",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "Panthera pardus",
        "habitat": "Forests, scrublands, rocky hills, and agricultural borders",
        "distribution": "Indian subcontinent",
        "diet": "Carnivorous, hunting deer, monkeys, wild pigs, and domestic dogs",
        "description": "A highly adaptable big cat species with rosette-patterned spots and powerful climbing ability.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Prevent human encroachment, check illegal snaring, and compensate livestock losses.",
        "human_wildlife_conflict_risk": "High risk in human-dominated landscapes near forest borders.",
        "anti_poaching_recommendation": "Patrol forest borders, dismantle illegal wire traps, and monitor waterholes.",
        "behaviour_hints": "Nocturnal, climbs trees to cache kills, solitary and highly elusive."
    },
    "Lion": {
        "common_name": "Asiatic Lion",
        "scientific_name": "Panthera leo persica",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "Panthera leo",
        "habitat": "Dry deciduous forests and dry savanna scrublands",
        "distribution": "Gir National Park and surrounding region in Gujarat, India",
        "diet": "Carnivorous, preying on deer, antelopes, wild boar, and cattle",
        "description": "An endangered subspecies of the lion, smaller and with a less developed mane than the African lion.",
        "iucn_status": "Endangered",
        "threat_level": "High",
        "conservation_priority": "Critical",
        "protection_recommendation": "Create a second reserve to prevent single-population disease extinction.",
        "human_wildlife_conflict_risk": "Medium-high risk; lives close to local cattle farms.",
        "anti_poaching_recommendation": "Enforce strict patrols, build open well safety parapets, and track radio collars.",
        "behaviour_hints": "Social, forms prides that are smaller than African counterparts, active at night."
    },
    "Lizard": {
        "common_name": "Lizard",
        "scientific_name": "Lacertilia",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Reptilia",
        "order": "Squamata",
        "family": "Gekkonidae",
        "genus": "Hemidactylus",
        "species": "Hemidactylus frenatus",
        "habitat": "Forest floor, trees, rocky cliffs, and stone walls",
        "distribution": "Worldwide, except polar regions",
        "diet": "Insectivorous, preying on flies, moths, crickets, and spiders",
        "description": "Widespread group of squamate reptiles with four limbs, external ears, and movable eyelids.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain rocky shelters and old wall habitats.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Prevent illegal collection of rare species for exotic pet trade.",
        "behaviour_hints": "Basks in sun to regulate body heat, drops tail when caught by predators."
    },
    "Lynx": {
        "common_name": "Lynx",
        "scientific_name": "Lynx lynx",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Lynx",
        "species": "Lynx lynx",
        "habitat": "Dense boreal forests and rocky mountain regions",
        "distribution": "Northern Europe, Asia, and North America",
        "diet": "Carnivorous, specializing in snowshoe hares, rabbits, and small deer",
        "description": "Medium-sized wild cats with thick fur, large padded paws, and characteristic black ear tufts.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Preserve old-growth forests and prevent decline of hare populations.",
        "human_wildlife_conflict_risk": "Low risk; rarely approaches human dwellings.",
        "anti_poaching_recommendation": "Check fur traps and establish strict hunting limits.",
        "behaviour_hints": "Highly secretive, solitary hunter, active primarily at night and dusk."
    },
    "Magpie": {
        "common_name": "Magpie",
        "scientific_name": "Pica pica",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Passeriformes",
        "family": "Corvidae",
        "genus": "Pica",
        "species": "Pica pica",
        "habitat": "Open countryside, woodlands, suburban gardens, and urban parks",
        "distribution": "Europe, Asia, and western North America",
        "diet": "Omnivorous, eating insects, seeds, fruits, small rodents, and carrion",
        "description": "Highly intelligent black and white birds in the crow family, known for a long tail.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Maintain mature tree lines and garden hedges.",
        "human_wildlife_conflict_risk": "Low risk, occasionally raids nests of songbirds in gardens.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Very curious, constructs massive domed stick nests, recognized for self-awareness."
    },
    "Monkey": {
        "common_name": "Bonnet Macaque",
        "scientific_name": "Macaca radiata",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Primates",
        "family": "Cercopithecidae",
        "genus": "Macaca",
        "species": "Macaca radiata",
        "habitat": "Deciduous forests, agricultural borders, and temple towns",
        "distribution": "Southern India",
        "diet": "Omnivorous, feeding on fruits, leaves, insects, flowers, and human food scraps",
        "description": "An endemic macaque species of southern India, recognizable by a cap-like whorl of hair.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "Medium",
        "protection_recommendation": "Avoid public feeding to prevent habituation and reduce urban waste access.",
        "human_wildlife_conflict_risk": "High risk of crop raiding and property theft in temples or roadsides.",
        "anti_poaching_recommendation": "Monitor forest edges and prevent capture for laboratory testing.",
        "behaviour_hints": "Highly social, lives in troops led by dominant males, uses facial expressions."
    },
    "Moths-and-butterflies": {
        "common_name": "Moths and Butterflies",
        "scientific_name": "Lepidoptera",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Insecta",
        "order": "Lepidoptera",
        "family": "Saturniidae",
        "genus": "Attacus",
        "species": "Attacus atlas",
        "habitat": "Forest canopy, meadows, agricultural crops, and home gardens",
        "distribution": "Worldwide, except polar regions",
        "diet": "Nectarivorous, feeding on plant nectar and pollen",
        "description": "An insect order containing both butterflies (day-flying) and moths (night-flying).",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Conserve wild larval host plants and eliminate pesticide usage.",
        "human_wildlife_conflict_risk": "Larvae cause agricultural leaf damage.",
        "anti_poaching_recommendation": "Regulate collection of giant silk moths in forest parks.",
        "behaviour_hints": "Moths fly to light sources at night, butterflies fold wings when resting."
    },
    "Mouse": {
        "common_name": "Mouse",
        "scientific_name": "Mus musculus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Rodentia",
        "family": "Muridae",
        "genus": "Mus",
        "species": "Mus musculus",
        "habitat": "Agricultural fields, houses, suburban areas, and grassy fields",
        "distribution": "Worldwide, associated with human dwellings",
        "diet": "Omnivorous, preying on seeds, grains, roots, insects, and human food scraps",
        "description": "A small rodent known for a pointed snout, large rounded ears, and a long scaly tail.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Manage agricultural crop storage and avoid chemical rodenticides that poison owls.",
        "human_wildlife_conflict_risk": "High risk of food contamination and property gnawing.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, high reproductive rate, nests in soft dark corners."
    },
    "Mule": {
        "common_name": "Mule",
        "scientific_name": "Equus mulus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Perissodactyla",
        "family": "Equidae",
        "genus": "Equus",
        "species": "Equus asinus x caballus",
        "habitat": "Farms, mountain paths, pasture lands, and stables",
        "distribution": "Worldwide, bred as working livestock",
        "diet": "Herbivorous, feeding on grasses, shrubs, hay, and grains",
        "description": "The hybrid offspring of a male donkey and a female horse, known for strength and endurance.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Ensure humane working conditions on mountain trails and prevent overworking.",
        "human_wildlife_conflict_risk": "Low risk, occasional crop damage if strayed.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Sure-footed, highly patient, avoids danger by stopping (often mistaken for stubborness)."
    },
    "Ostrich": {
        "common_name": "Ostrich",
        "scientific_name": "Struthio camelus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Struthioniformes",
        "family": "Struthionidae",
        "genus": "Struthio",
        "species": "Struthio camelus",
        "habitat": "Dry savannas, open semi-deserts, and scrublands",
        "distribution": "Sub-Saharan Africa",
        "diet": "Omnivorous, feeding on plant roots, seeds, leaves, lizards, and insects",
        "description": "The largest and heaviest living bird species, which is flightless but can run at high speeds.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Manage savanna grazing lands and prevent conversion of scrublands to agriculture.",
        "human_wildlife_conflict_risk": "Low risk, can deliver powerful kicks if cornered.",
        "anti_poaching_recommendation": "Monitor egg collection in dry desert parks.",
        "behaviour_hints": "Very fast runner, rolls head on ground when hiding, swallows sand for digestion."
    },
    "Otter": {
        "common_name": "Otter",
        "scientific_name": "Lutrinae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Mustelidae",
        "genus": "Lutra",
        "species": "Lutra lutra",
        "habitat": "Rivers, lakes, marshes, and coastal water channels",
        "distribution": "Worldwide, except Australia and Antarctica",
        "diet": "Carnivorous, preying on fish, frogs, crabs, and water birds",
        "description": "Sleek, semi-aquatic mammals with webbed feet and water-repellent dense fur.",
        "iucn_status": "Near Threatened",
        "threat_level": "Low",
        "conservation_priority": "Moderate",
        "protection_recommendation": "Clean freshwater wetlands, eliminate illegal sand mining, and ban otter skin trading.",
        "human_wildlife_conflict_risk": "Low risk, occasionally raids local fish farming ponds.",
        "anti_poaching_recommendation": "Conduct river patrols and dismantle illegal gill nets.",
        "behaviour_hints": "Playful, slides down mud banks, forms tight family groups, active hunter."
    },
    "Owl": {
        "common_name": "Owl",
        "scientific_name": "Strigiformes",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Strigiformes",
        "family": "Strigidae",
        "genus": "Bubo",
        "species": "Bubo bubo",
        "habitat": "Forest canopy, deserts, farm barns, and rocky crevices",
        "distribution": "Worldwide, except Antarctica",
        "diet": "Carnivorous, hunting mice, rats, beetles, frogs, and small birds",
        "description": "Solitary nocturnal birds of prey with forward-facing eyes and silent flight feathers.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Retain hollow nesting trees and reduce pesticide use to preserve rodent prey.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Prevent illegal trapping of owls for ritual practices during festivals.",
        "behaviour_hints": "Silent flight, produces regurgitated pellets, turns head up to 270 degrees."
    },
    "Panda": {
        "common_name": "Giant Panda",
        "scientific_name": "Ailuropoda melanoleuca",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ursidae",
        "genus": "Ailuropoda",
        "species": "Ailuropoda melanoleuca",
        "habitat": "High-altitude damp bamboo forests",
        "distribution": "Central China mountain ranges",
        "diet": "Herbivorous, feeding almost exclusively on bamboo shoots and leaves",
        "description": "Distinctive black and white bear species native to China, which has a pseudo-thumb to hold bamboo.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Reconnect fragmented bamboo reserves and prevent human forest encroachment.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Enforce strict penalties for bamboo harvesting and trap setting in reserves.",
        "behaviour_hints": "Solitary, spends up to 12 hours a day feeding, excellent tree climber."
    },
    "Parrot": {
        "common_name": "Parrot",
        "scientific_name": "Psittaciformes",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Psittaciformes",
        "family": "Psittaculidae",
        "genus": "Psittacula",
        "species": "Psittacula krameri",
        "habitat": "Tropical rainforests, woodlands, savannahs, and urban parks",
        "distribution": "Tropical and subtropical regions worldwide",
        "diet": "Herbivorous, feeding on seeds, nuts, fruit, flower buds, and nectar",
        "description": "Brightly colored birds characterized by strong curved bills, upright stance, and intelligence.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect rainforest nest hollows and prohibit illegal songbird trading.",
        "human_wildlife_conflict_risk": "Low risk, occasionally damages fruit orchards.",
        "anti_poaching_recommendation": "Monitor forest nesting sites and borders for bird netting.",
        "behaviour_hints": "Highly vocal, mimics sounds, flies in screeching flocks, uses claws to hold food."
    },
    "Peacock": {
        "common_name": "Indian Peafowl",
        "scientific_name": "Pavo cristatus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Galliformes",
        "family": "Phasianidae",
        "genus": "Pavo",
        "species": "Pavo cristatus",
        "habitat": "Dry deciduous forests, scrublands, and agricultural clearings",
        "distribution": "South Asia, introduced globally",
        "diet": "Omnivorous, feeding on seeds, fruits, grain, small snakes, and insects",
        "description": "The national bird of India, celebrated for the male's iridescent blue neck and fan tail.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect nesting undergrowth and restrict use of chemical seed treatments.",
        "human_wildlife_conflict_risk": "Low risk, feeds on crops near villages and produces loud calling.",
        "anti_poaching_recommendation": "Monitor feather harvesting and inspect forest fringes.",
        "behaviour_hints": "Roosts on high branches, performs fan display to attract females, vocalizes loudly during monsoon."
    },
    "Pig": {
        "common_name": "Pig",
        "scientific_name": "Sus scrofa domesticus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Suidae",
        "genus": "Sus",
        "species": "Sus scrofa",
        "habitat": "Farms, pastures, grasslands, and woodlands",
        "distribution": "Worldwide, domestic species",
        "diet": "Omnivorous, eating roots, grains, fruits, vegetables, and small invertebrates",
        "description": "Domesticated omnivorous hoofed mammal, widely bred for meat production.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Improve farm biosecurity to avoid African swine fever transmission to wild boars.",
        "human_wildlife_conflict_risk": "Low risk, can escape and form invasive feral populations.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Very intelligent, wallows in mud to cool down, roots in soil with snout."
    },
    "Polar-bear": {
        "common_name": "Polar Bear",
        "scientific_name": "Ursus maritimus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ursidae",
        "genus": "Ursus",
        "species": "Ursus maritimus",
        "habitat": "Arctic sea ice, pack ice, and coastal tundra coasts",
        "distribution": "Arctic Circle region",
        "diet": "Carnivorous, specializing on ringed and bearded seals",
        "description": "The largest species of bear, highly adapted for swimming and survival in freezing temperatures.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Combat global warming to protect sea ice, and reduce industrial drilling in the Arctic.",
        "human_wildlife_conflict_risk": "High risk of attack near northern garbage sites when sea ice melts.",
        "anti_poaching_recommendation": "Patrol coastal den locations and monitor sea channels.",
        "behaviour_hints": "Superb swimmer, solitary, uses white camouflage fur to stalk seals at breathing holes."
    },
    "Rabbit": {
        "common_name": "Rabbit",
        "scientific_name": "Oryctolagus cuniculus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Lagomorpha",
        "family": "Leporidae",
        "genus": "Oryctolagus",
        "species": "Oryctolagus cuniculus",
        "habitat": "Meadows, grasslands, woodlands, sand dunes, and home gardens",
        "distribution": "Global distribution",
        "diet": "Herbivorous, grazing on grasses, weeds, leaves, bark, and crops",
        "description": "Small mammals with long ears, fluffy short tails, and strong hind legs for hopping.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect natural predators (hawks, foxes) to keep populations in check.",
        "human_wildlife_conflict_risk": "High risk of garden damage and crop loss.",
        "anti_poaching_recommendation": "Monitor netting in agricultural fields.",
        "behaviour_hints": "Crepuscular, lives in underground burrow networks called warrens."
    },
    "Raccoon": {
        "common_name": "Raccoon",
        "scientific_name": "Procyon lotor",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Procyonidae",
        "genus": "Procyon",
        "species": "Procyon lotor",
        "habitat": "Deciduous forests, marshes, and urban residential zones",
        "distribution": "North America, introduced to Europe and Japan",
        "diet": "Omnivorous, consuming insects, fruits, nuts, small frogs, eggs, and garbage",
        "description": "Medium-sized mammal recognizable by its black facial mask and ringed bushy tail.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Enforce secure waste bin guidelines in suburban areas.",
        "human_wildlife_conflict_risk": "Medium-high risk of attic nesting and trash bin raiding.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, highly dexterous front paws, washes food in water."
    },
    "Raven": {
        "common_name": "Raven",
        "scientific_name": "Corvus corax",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Passeriformes",
        "family": "Corvidae",
        "genus": "Corvus",
        "species": "Corvus corax",
        "habitat": "Forests, deserts, mountain cliffs, and tundra plains",
        "distribution": "Northern Hemisphere",
        "diet": "Omnivorous, feeding on carrion, small rodents, insects, seeds, and garbage",
        "description": "Large all-black passerine bird, highly intelligent and adaptable.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Ensure safe nesting structures and prevent poisoning from carcass lead bullets.",
        "human_wildlife_conflict_risk": "Low risk, occasionally takes newborn lambs.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Excellent vocal mimicry, aerodynamically agile, works in pairs to scavenge."
    },
    "Red-panda": {
        "common_name": "Red Panda",
        "scientific_name": "Ailurus fulgens",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Ailuridae",
        "genus": "Ailurus",
        "species": "Ailurus fulgens",
        "habitat": "High-altitude deciduous and coniferous forests with bamboo understory",
        "distribution": "Eastern Himalayas, including Nepal, India, Bhutan, and China",
        "diet": "Herbivorous, feeding primarily on bamboo leaves and shoots, berries, and mushrooms",
        "description": "Small arboreal mammal with reddish-brown fur, a long shaggy tail, and a bear-like face.",
        "iucn_status": "Endangered",
        "threat_level": "High",
        "conservation_priority": "Critical",
        "protection_recommendation": "Protect bamboo understory, eliminate illegal logging, and prevent dog disease transmission.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "Patrol mountain habitats and prevent trapping for the illegal pet trade.",
        "behaviour_hints": "Arboreal, nocturnal and crepuscular, wraps tail around body to keep warm."
    },
    "Rhinoceros": {
        "common_name": "Indian Rhinoceros",
        "scientific_name": "Rhinoceros unicornis",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Perissodactyla",
        "family": "Rhinocerotidae",
        "genus": "Rhinoceros",
        "species": "Rhinoceros unicornis",
        "habitat": "Alluvial grasslands and riverine swamp forests",
        "distribution": "Northern India (primarily Assam) and Nepal",
        "diet": "Herbivorous, feeding on tall grasses, aquatic plants, and tree branches",
        "description": "Also known as the Greater One-horned Rhino, recognized by its armor-like skin folds.",
        "iucn_status": "Vulnerable",
        "threat_level": "Medium",
        "conservation_priority": "High",
        "protection_recommendation": "Restore alluvial grasslands, suppress invasive weeds, and expand protected areas.",
        "human_wildlife_conflict_risk": "Medium risk, occasionally enters agricultural fields to feed on crops.",
        "anti_poaching_recommendation": "Deploy armed forest rangers, use drone thermal cameras, and monitor horn trading.",
        "behaviour_hints": "Solitary, enjoys wallowing in muddy swamps, possesses excellent hearing and smell."
    },
    "Scorpion": {
        "common_name": "Scorpion",
        "scientific_name": "Scorpiones",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Arachnida",
        "order": "Scorpiones",
        "family": "Buthidae",
        "genus": "Androctonus",
        "species": "Androctonus australis",
        "habitat": "Deserts, dry grasslands, caves, and under rock crevices",
        "distribution": "Worldwide, except polar regions",
        "diet": "Carnivorous, hunting insects, spiders, and small lizards",
        "description": "Predatory arachnids characterized by a segment tail tipped with a venomous stinger and grasping pincers.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Conserve dry scrublands and avoid collecting wild specimens.",
        "human_wildlife_conflict_risk": "Possess painful venomous sting; can enter houses in arid zones.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Nocturnal, glows under ultraviolet blacklight, uses pincers to hold prey."
    },
    "Sheep": {
        "common_name": "Sheep",
        "scientific_name": "Ovis aries",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Bovidae",
        "genus": "Ovis",
        "species": "Ovis aries",
        "habitat": "Grasslands, pastures, uplands, and farm hillsides",
        "distribution": "Worldwide, domestic species",
        "diet": "Herbivorous, grazing on short grasses and clover",
        "description": "Domesticated ruminant mammals kept as livestock for wool, milk, and meat.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Prevent overgrazing in arid pastures and vaccinate flocks against disease.",
        "human_wildlife_conflict_risk": "Attracts large predators (wolves, snow leopards), leading to predator poisoning.",
        "anti_poaching_recommendation": "Deploy guard dogs (e.g. Anatolians) to reduce predation losses.",
        "behaviour_hints": "Strong flocking instinct, follows a leader, highly sensitive to sudden movements."
    },
    "Snake": {
        "common_name": "Snake",
        "scientific_name": "Serpentes",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Reptilia",
        "order": "Squamata",
        "family": "Colubridae",
        "genus": "Elaphe",
        "species": "Elaphe obsoleta",
        "habitat": "Forests, grasslands, swamps, deserts, and agricultural fields",
        "distribution": "Worldwide, except polar regions",
        "diet": "Carnivorous, preying on rodents, birds, frogs, and eggs",
        "description": "Elongated, legless, carnivorous squamate reptiles, some of which possess venomous bites.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Avoid indiscriminate killing of snakes and preserve forest undergrowth.",
        "human_wildlife_conflict_risk": "High risk of venomous bites during farming operations.",
        "anti_poaching_recommendation": "Prevent skin trade collection and patrol rocky areas.",
        "behaviour_hints": "Shed skin regularly, uses tongue to smell, relies on vibrations to detect threats."
    },
    "Sparrow": {
        "common_name": "House Sparrow",
        "scientific_name": "Passer domesticus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Passeriformes",
        "family": "Passeridae",
        "genus": "Passer",
        "species": "Passer domesticus",
        "habitat": "Urban areas, agricultural farms, gardens, and villages",
        "distribution": "Worldwide, closely associated with human settlements",
        "diet": "Granivorous, eating seeds, grain, weed seeds, and small insects",
        "description": "Small passerine bird, characterized by brown and grey plumage and a chirping call.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Install nesting boxes in residential areas and plant native shrubs.",
        "human_wildlife_conflict_risk": "No conflict risk.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Highly social, dust-bathes in small groups, nests in building cavities."
    },
    "Spider": {
        "common_name": "Spider",
        "scientific_name": "Araneae",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "class_name": "Arachnida",
        "order": "Araneae",
        "family": "Araneidae",
        "genus": "Araneus",
        "species": "Araneus diadematus",
        "habitat": "Forests, meadows, agricultural crops, gardens, and houses",
        "distribution": "Worldwide, except Antarctica",
        "diet": "Carnivorous, preying on flies, moths, beetles, and other small insects",
        "description": "Air-breathing arthropods with eight legs and chelicerae modified into venomous fangs.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Avoid using chemical insecticides that reduce spider populations.",
        "human_wildlife_conflict_risk": "Low risk; most spider bites are harmless, but some species are medically significant.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Spins silk orb webs to capture flying prey, senses prey via vibrations."
    },
    "Swan": {
        "common_name": "Swan",
        "scientific_name": "Cygnus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Anseriformes",
        "family": "Anatidae",
        "genus": "Cygnus",
        "species": "Cygnus olor",
        "habitat": "Lakes, ponds, slow-moving rivers, and coastal bays",
        "distribution": "Northern and Southern Hemispheres",
        "diet": "Herbivorous, consuming submerged aquatic vegetation and pond weeds",
        "description": "Large elegant waterfowl known for their long curved necks and white feathers.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect freshwater shorelines and prevent ingestion of toxic lead fishing sinkers.",
        "human_wildlife_conflict_risk": "Low risk, can be highly protective and aggressive during nesting season.",
        "anti_poaching_recommendation": "Check nesting waters during spring season.",
        "behaviour_hints": "Mates for life, carries cygnets on back, defensive wing-hissing posture."
    },
    "Tiger": {
        "common_name": "Bengal Tiger",
        "scientific_name": "Panthera tigris tigris",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Felidae",
        "genus": "Panthera",
        "species": "Panthera tigris",
        "habitat": "Tropical forests, mangrove swamps, and tall alluvial grasslands",
        "distribution": "Indian subcontinent, mainly India",
        "diet": "Carnivorous, hunting deer, wild boar, gaurs, and domestic cattle",
        "description": "The largest wild cat species in the world, recognizable by its orange coat with black stripes.",
        "iucn_status": "Endangered",
        "threat_level": "High",
        "conservation_priority": "Critical",
        "protection_recommendation": "Restore tiger reserves, stop illegal logging, and increase prey populations.",
        "human_wildlife_conflict_risk": "High risk of attack on humans or cattle in buffer villages.",
        "anti_poaching_recommendation": "Deploy armed anti-poaching camps, patrol waterholes, and monitor snare traps.",
        "behaviour_hints": "Solitary, excellent swimmer, uses stripe camouflage to stalk prey close up."
    },
    "Turkey": {
        "common_name": "Turkey",
        "scientific_name": "Meleagris gallopavo",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Galliformes",
        "family": "Phasianidae",
        "genus": "Meleagris",
        "species": "Meleagris gallopavo",
        "habitat": "Deciduous forests, open woodlands, scrublands, and pastures",
        "distribution": "North America; domesticated globally",
        "diet": "Omnivorous, foraging on acorns, seeds, berries, leaves, and insects",
        "description": "Large poultry bird native to North America, characterized by a fleshy wattle.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Protect oak forests and control wild turkey hunting seasons.",
        "human_wildlife_conflict_risk": "Low risk, can be bold in suburban streets.",
        "anti_poaching_recommendation": "Check hunting licenses and limits during spring.",
        "behaviour_hints": "Roosts in trees at night, struts and gobbles to display to hens."
    },
    "Wild Boar": {
        "common_name": "Indian Boar",
        "scientific_name": "Sus scrofa cristatus",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Artiodactyla",
        "family": "Suidae",
        "genus": "Sus",
        "species": "Sus scrofa",
        "habitat": "Deciduous forests, scrublands, and agricultural borders",
        "distribution": "South Asia, including India and Nepal",
        "diet": "Omnivorous, feeding on roots, tubers, agricultural crops, carrion, and insects",
        "description": "A subspecies of wild boar distinguished by a mane of long bristles along its back.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Use solar fencing around cropland and protect natural forest predators.",
        "human_wildlife_conflict_risk": "High risk of crop raiding and occasional charges at farmers.",
        "anti_poaching_recommendation": "Check border traps and prevent night hunting.",
        "behaviour_hints": "Forms social groups called sounders, active at night, digs up soil to find food."
    },
    "Wolf": {
        "common_name": "Indian Wolf",
        "scientific_name": "Canis lupus pallipes",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Carnivora",
        "family": "Canidae",
        "genus": "Canis",
        "species": "Canis lupus",
        "habitat": "Scrublands, open grasslands, and semi-arid desert borders",
        "distribution": "Indian subcontinent and western Asia",
        "diet": "Carnivorous, preying on antelopes, hares, rodents, and livestock",
        "description": "A smaller, more slender subspecies of the gray wolf adapted for hot, arid climates.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Establish grasslands reserves and pay quick compensation for livestock loss.",
        "human_wildlife_conflict_risk": "Medium-high risk due to pasture grazing and livestock attacks.",
        "anti_poaching_recommendation": "Patrol open plains and restrict pastoralist poison baiting.",
        "behaviour_hints": "Forms small packs, silent hunter, communicates via howling and postures."
    },
    "Woodpecker": {
        "common_name": "Woodpecker",
        "scientific_name": "Picidae",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Aves",
        "order": "Piciformes",
        "family": "Picidae",
        "genus": "Dendrocopos",
        "species": "Dendrocopos major",
        "habitat": "Forest woodlands, orchards, and parks with mature trees",
        "distribution": "Global distribution",
        "diet": "Insectivorous, tapping tree bark to extract grubs, beetles, and ants",
        "description": "Birds specialized for climbing trees, drumming on trunks with strong chisel bills.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Retain standing dead trees (snags) which serve as nesting cavities.",
        "human_wildlife_conflict_risk": "Low risk, can drum on building siding.",
        "anti_poaching_recommendation": "No anti-poaching measures required.",
        "behaviour_hints": "Clings vertically to tree trunks, drums rhythmically, nesting in self-excavated holes."
    },
    "Zebra": {
        "common_name": "Zebra",
        "scientific_name": "Equus quagga",
        "kingdom": "Animalia",
        "phylum": "Chordata",
        "class_name": "Mammalia",
        "order": "Perissodactyla",
        "family": "Equidae",
        "genus": "Equus",
        "species": "Equus quagga",
        "habitat": "Treeless grasslands and herbaceous savannah woodlands",
        "distribution": "Eastern and southern Africa",
        "diet": "Herbivorous, grazing on coarse grasses and tall vegetation",
        "description": "African equids best known for their unique black and white striped coats.",
        "iucn_status": "Least Concern",
        "threat_level": "Low",
        "conservation_priority": "Routine",
        "protection_recommendation": "Preserve migratory grazing pathways and protect water access points.",
        "human_wildlife_conflict_risk": "Low risk, occasional crop grazing.",
        "anti_poaching_recommendation": "Patrol migration routes to prevent wire snaring.",
        "behaviour_hints": "Highly social, forms harems or bachelor herds, relies on striping to confuse predators."
    }
}

# Read existing catalog
if os.path.exists(catalog_path):
    with open(catalog_path, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {
        "version": "1.0",
        "description": "WPIS Species Knowledge Base — curated Indian and global wildlife profiles",
        "species": [],
        "gemini_generated": []
    }

species_list = data.get("species", [])
gemini_generated = data.get("gemini_generated", [])

# Let's clean up existing species list and replace/append complete info for all 64 classes
class_norm_map = {}
for k in class_data.keys():
    class_norm_map[k.lower().replace("-", " ")] = k

# Update species list
updated_count = 0
added_count = 0

for cls_key, cls_info in class_data.items():
    norm_cls = cls_key.lower().replace("-", " ")
    matched_idx = -1
    
    # Try finding existing entry
    for i, s in enumerate(species_list):
        common = s.get("common_name", "").lower().replace("-", " ")
        scientific = s.get("scientific_name", "").lower()
        aliases = [a.lower().replace("-", " ") for a in s.get("aliases", [])]
        if norm_cls == common or norm_cls == scientific or norm_cls in aliases:
            matched_idx = i
            break
            
    # Set default aliases
    aliases = [cls_info["common_name"], cls_info["common_name"].lower()]
    if cls_key != cls_info["common_name"]:
        aliases.append(cls_key)
        aliases.append(cls_key.lower())
    cls_info["aliases"] = sorted(list(set(aliases)))
    
    if matched_idx >= 0:
        # Merge, keeping existing fields but overwriting placeholders/missing
        existing = species_list[matched_idx]
        # Overwrite all fields from cls_info to ensure it's complete and valid
        for field, val in cls_info.items():
            existing[field] = val
        updated_count += 1
    else:
        # Append as new
        species_list.append(cls_info)
        added_count += 1

# Overwrite database to save space and keep sorted
data["species"] = sorted(species_list, key=lambda x: x.get("common_name", ""))
data["gemini_generated"] = sorted(list(set(gemini_generated)))

with open(catalog_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} species profiles; Added {added_count} species profiles. Total entries: {len(data['species'])}")
